import bcrypt from "bcryptjs";

export const users = [
  {
    fname: "Meron",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/2.jpg",
  },
  {
    fname: "Aster",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuka.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/3.jpg",
  },
  {
    fname: "Kefa",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/4.jpg",
  },
  {
    fname: "Zemen",
    lname: "Kebede",
    profilepic: "/users/5.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Zinash",
    lname: "Amare",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "ziniabiy.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/6.jpg",
  },
  {
    fname: "Zenit",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/7.jpg",
  },
  {
    fname: "Zerfe",
    lname: "Moges",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerfe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/8.jpg",
  },
  {
    fname: "Manaye",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mana.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/10.jpg",
  },
  {
    fname: "Zetseat",
    lname: "Ferede",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zetsu.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/11.jpg",
  },
  {
    fname: "Bereket",
    lname: "Asseffa",
    profilepic: "/users/12.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "beki.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Afomia",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "afomi.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/13.jpg",
  },
  {
    fname: "Menberu",
    lname: "Zemi",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menbe.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/14.jpg",
  },
  {
    fname: "Haymi",
    lname: "Alaska",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyami.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/15.jpg",
  },
  {
    fname: "Tomas",
    lname: "Kerebih",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri1.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/16.jpg",
  },
  {
    fname: "Dawit",
    lname: "Molalign",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuk2.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/17.jpg",
  },
  {
    fname: "Mazengia",
    lname: "Asgedom",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa3.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/18.jpg",
  },
  {
    fname: "Lij Yared",
    lname: "Kebede",
    profilepic: "/users/19.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu4.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Enatnesh",
    lname: "Kelemu",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "ziniabiy5.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/20.jpg",
  },
  {
    fname: "Zemenay",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii6.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/21.jpg",
  },
  {
    fname: "Rebeka",
    lname: "Alene",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerfe7.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/22.jpg",
  },
  {
    fname: "Zenaw",
    lname: "Abebe",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "mana8.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/23.jpg",
  },
  {
    fname: "Feleke",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zetsu9.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/24.jpg",
  },
  {
    fname: "Beki",
    lname: "Amare",
    profilepic: "/users/25.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "beki77.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Afewerk",
    lname: "Anagaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "afomi99.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/26.jpg",
  },
  {
    fname: "neberu",
    lname: "Shegaw",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "menbe555.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/27.jpg",
  },
  {
    fname: "Asnake",
    lname: "Yekoye",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "hyami875.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/28.jpg",
  },
  {
    fname: "Ermiyas",
    lname: "Tegegn",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "meri66.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/29.jpg",
  },
  {
    fname: "Aster",
    lname: "Kelemu",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "astuka912.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/30.jpg",
  },
  {
    fname: "Yisak",
    lname: "Mengesha",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "keffamideksa98.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/31.jpg",
  },
  {
    fname: "Meles",
    lname: "Tigray",
    profilepic: "/users/32.jpg",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "zemenu4zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
  },
  {
    fname: "Mekbib",
    lname: "Fetene",
    birthDay: new Date(),
    gender: "male",
    mobileOrPhoneNumber: "ziniabiy786.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/33.jpg",
  },
  {
    fname: "Elsabet",
    lname: "Molla",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "amanii33.zii@gmail.com",
    password: bcrypt.hashSync("zenit.Oath.49", 10),
    profilepic: "/users/34.jpg",
  },
  {
    fname: "Dibora",
    lname: "Moges",
    birthDay: new Date(),
    gender: "female",
    mobileOrPhoneNumber: "zerf33e.zi@gmail.com",
    password: bcrypt.hashSync("Fb.Oath.49", 10),
    profilepic: "/users/35.jpg",
  },
];
